# Generated by Django 3.2.7 on 2021-12-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100)),
                ('featured_image', models.ImageField(upload_to='blog/featrued_image/')),
                ('main_image', models.ImageField(upload_to='blog/main_image/')),
                ('content', models.TextField()),
            ],
        ),
    ]
