# Generated by Django 3.2.7 on 2021-12-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
